name: ABT Node deployment
on:
  push:
    branches:
      - main
      - master
jobs:
  Deploy:
    runs-on: ubuntu-latest
    if: "! contains(toJSON(github.event.commits.*.message), '[skip ci]')"
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set yarn cache
        uses: c-hive/gha-yarn-cache@v2

      - name: Init
        run: make github-action-init

      - name: Blocklet workflow
        uses: blocklet/action-workflow@v1.1
        with:
          skip-upload: false
          skip-deploy: false
          bundle-command: yarn bundle
          store-endpoint: ${{ secrets.STORE_ENDPOINT_PROD }}
          store-access-token: ${{ secrets.STORE_ACCESS_TOKEN_PROD }}
          abtnode-endpoint: ${{ secrets.AWS_NODE_ENDPOINT }}
          access-key: ${{ secrets.AWS_NODE_ACCESS_KEY }}
          access-secret: ${{ secrets.AWS_NODE_ACCESS_SECRET }}
          slack-webhook: ${{ secrets.SLACK_WEBHOOK }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy to Aliyun
        uses: blocklet/action-workflow@v1.1
        with:
          skip-abtnode: true
          skip-bundle: true
          skip-deploy: false
          skip-release: true
          abtnode-endpoint: ${{ secrets.ALIYUN_NODE_ENDPOINT }}
          access-key: ${{ secrets.ALIYUN_NODE_ACCESS_KEY }}
          access-secret: ${{ secrets.ALIYUN_NODE_ACCESS_SECRET }}
          slack-webhook: ${{ secrets.SLACK_WEBHOOK }}
